// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPlKqnWnnS3OTNX_ZJhOjcidTpu4Og_DE',
    appId: '1:1097564180596:web:d35cfb58ad7393d53b8121',
    messagingSenderId: '1097564180596',
    projectId: 'attendant-management',
    authDomain: 'attendant-management.firebaseapp.com',
    storageBucket: 'attendant-management.appspot.com',
    measurementId: 'G-WMHTM4NLZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ko60V4WaFVEUWnmfcIQA0_L9Z_BQAkQ',
    appId: '1:1097564180596:android:8282dec74cff90a13b8121',
    messagingSenderId: '1097564180596',
    projectId: 'attendant-management',
    storageBucket: 'attendant-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzpPisT9ZYP7fLZ-NoM5--Ty-own_jrY',
    appId: '1:1097564180596:ios:b4b994ef471a837d3b8121',
    messagingSenderId: '1097564180596',
    projectId: 'attendant-management',
    storageBucket: 'attendant-management.appspot.com',
    iosBundleId: 'com.example.workCompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlzpPisT9ZYP7fLZ-NoM5--Ty-own_jrY',
    appId: '1:1097564180596:ios:b4b994ef471a837d3b8121',
    messagingSenderId: '1097564180596',
    projectId: 'attendant-management',
    storageBucket: 'attendant-management.appspot.com',
    iosBundleId: 'com.example.workCompass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPlKqnWnnS3OTNX_ZJhOjcidTpu4Og_DE',
    appId: '1:1097564180596:web:c94e44210ba9f0643b8121',
    messagingSenderId: '1097564180596',
    projectId: 'attendant-management',
    authDomain: 'attendant-management.firebaseapp.com',
    storageBucket: 'attendant-management.appspot.com',
    measurementId: 'G-DWP3GKRP3M',
  );

}